name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    env:
      SENTRY_SECRET: ${{ secrets.SENTRY_SECRET }}
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Build gatsby site
        run: npm run build

      - name: Deploy site
        run: |
          git config user.name "SLedunois" && git config user.email "simon.ledunois@gmail.com"
          git remote add ci https://sledunois:${{ secrets.CI_TOKEN }}@github.com/SLedunois/sledunois.github.io.git
          git --work-tree public add --all
          git --work-tree public commit -m "Deploy sledunois.github.io"
          git push ci HEAD:master --force
          rm -r public
          git checkout -f master
